travis:
  secure:
    BINSTAR_TOKEN: mW1eGbAMg7jTev0wnsMETQKLFICkz9M3Ep5NvjYO2QTQMZNXiha0CT5Qn3TbKXyZskWqmbYBcBK1uUGo3uc1nZe8u5lzaDtF44cFoEMlHPq/y1p88wy7zDnRbUQ9HK+daDdzZt1r1NMcGxjKb9Si9e/1oUvzLlTBCmF0RQ2+HLiri2tVLIaCA2P9KwG3I9mt7M/HkyLVD2JV4yyUEcOwVHshfYoF7iNGQi9MzndxDSxnZ/BHE1BnRa/PlY6rD5KUPdWPcqdWZgL7/vrEIbC4U1Z3bb2E7tGdS44uBYSjtOYnzxqok5jD9Fs7GY68pQBmTTVvR9A4P8t3kpe6KntyemDHwV997OuJ2q3idmHefFo/S9Px6f1fwZjWQ10yqtEPJyOsbfx9Wkj6MngsH1e3mHvjUUtz3V+SnfTnglBXgnzEX29z4d3Z8/wzJCxk0wOghKtrrBz3O3MltMlcC9ujmiR4d5LOwd1YO0kAilyQk0lyoNgU98G8TS0YhvxxVECxbk2a4yUwFZ6n0FM3O9LcRy40MZJMnlnFvBfu8Kp8eLzEzsvVtp8FfcLE0KqwEKwjPnHE+Mv5pSJas8Qi8khWT8ZYPi/UnymXR6iaJX027QPnoH42Zjk5RRHOQQbGul5EsSIURRvFBI1PvLxRr+GmmG7ls1GdX8XF8D/xySGxvcI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
