travis:
  secure:
    BINSTAR_TOKEN: WkRX1bPqDSANaah5QFg366TYmqMSHXqgzneyoFA2CWkshiy4ioS4eIzno82ir2P9CKRA/8iAlZpGFNYHZv1RTg4JcpI9n/7RrWv8GMxvQiUI/0tsBAC1cVD5ftljCxrNRtwXeqbXDapTdkzPF5b0jEeO2Toht2CWqx1SOnUgagDXCr7cIT69IHjwz1oTuIZQE65WFq1nYH2Fv7+5G6ArkF5+5P+xFJnykC7lgnsM6OxwblkBBqax0nti538ZtuxEpVTtRJDFRoo5di51yqMkXGiLuUv8hBfaBaeZildazPgn6tBUGK8wQ4pkUCiwaFz4DmR+y3pA4DvpXKtsJJw2IY5Rj5Infas3Y1kVUTvbc+8u9XU/4XZyoHRbtVVwZHCB6xxTLr3sMBqP63qrnx0rns/0V3SLRakjd6Gr/W+SkGuBGow3f7J4ualXGucU3eB31wDaNMgEoEBcpvWjqFufKyu6tvffIC2Fu0vv+Skwtreoysq4zlV0nyKwj0+2vMbVHPJDGrNVRPeFtuf+QSQt9i1F1MZn8l39N+jtUARGbVKK8S1H8UvIKksfcD1HbaE73m4XF9C/nemwpuugzbJ0hzx5Y36KXgPGj6yyPbmX9Fk4/26ioo/nN0R/Wszd+NRRZqDkYan+nyCLrIQmNRgemjkhLT6D3uyfsCjUEPudQqI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
