travis:
  secure:
    BINSTAR_TOKEN: nLdbJXZgqOM7OZdsJPxsTw0XCMBmKSZVq8nEtzeVpwJxufmqRlUBls6Agu8vtmrij0MgcKl3hEaMAA5EIaBdWgzwh3Sd40/aRHZIfevTAGNJtNKkEiCJZcTUvWRcWKWV/2HZJ6fj+UcJspCzYInftPCdG41OhajzCkhQL/K3POVrvbkrsp7uHuXrmRYMq0ustO8SblTj6sySjKhT7f9H9tpFQcsL4n7OTy6JEAFsJn+HfRwsWQL7/1A+CICgBxS9O+hJ2BaTP4xq4OL6256ZAVBr7zItvJyG4vCzKGY3NcFuQUFfBcWb07qiDA5ToZ+2XoyITawCeZNbej8X1ygf1tFNuxbbJh2Yz1ZcjZ473t4Tb8FOOeRvzFopcgE+41RpXLlFZUR3kOntvUwNdgka/W6Wj6W3FBwNsx+sARRbog3apo4HYZBjWfx0hYRstlSTT6WhxVPYsDYuc1XPk7jgqW2g9X1Km+07kkE1XsM/4ugABIDzLdwGAxNA7QlyKRWzaJW5r7Hj8Zoif6LV7X/9eq361/rfhPnV8MIl4Ecm4p71Unb0o9VyqHy40fpel/GToYYlxC3B2CfDz7bryaL/qqTMLwCbAKWYXt5q/oPXN2jX6fhyVAbmBK6lsHZZprTpe8VTecOQgmFRHQis4GIJDfS7I0RyTkWqEUehivGx5s8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
