travis:
  secure:
    BINSTAR_TOKEN: iAsUu6PggCYjZZ/4ebU5Xuek1Qah07GacDIaSdSqsNCO+VojqB/jJBMkdK72xxDfazk6YlrkCDBK0b6Go3OpFejLjOzETltOqq0jlaaI/5sBiAGSy/BzO0RBwutyRI7698bUhXFLrROO+KvZBdpbFHHD2nIkKpmN81EUlMxfs0nW9d+VZAfPod/pWRJmll39vu0e2HPRNFzMtbgdhRNONBOl+FrFzTriDvYUPvrDXbPnmFi/P7mlaQN5RcBSMX8tENl6qtIINxxZKRx2ouVVYyWrmVaCYDrOZCHWC8mrYsYmvbEyLCfUwE8SMRAl83Z/DegLhF6w2ilb+2IEVCAssM/UHA4M4m9Bcq74ubCYylAprDw37crsjz2xvFNJw+RFV8XjJXMse6TTfMoP0OC+8AycqPNtxd2vIpnIzZs7ITiJ/Ki33lxikeDDPIklX39XaQZdL6iUeNGHwp5yy84gz1Px+jygUhhTlgp2PHSfjLEUobIJb2BNv0rJ0y0LKgBgAJPQOMAUhs1jb4LTrz8Ao3VzK+Hoycw2Xe5ZCfU5S8Ted9rJyKf0wprClqzhPH7gYg4H1x9H6P9jmkLa7q2jnJHwH6iKjblYgUmCQNviIZk7mKPpaInAEbsQzxSEmJhfQ1qH2ZjOAuZH1XDdiAbdwvBo5+SwFacV20YToOw4WuM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
